apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . 10.129.51.250
        cache 30
    }
kind: ConfigMap
metadata:
  creationTimestamp: 2018-08-22T03:41:51Z
  name: coredns
  namespace: kube-system
  resourceVersion: "73641895"
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
  uid: 4e004e43-a5bd-11e8-a33b-060eb4000e9d
